# Generated by Django 2.2.14 on 2020-11-29 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_column='STR_NOME', max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Conta',
                'verbose_name_plural': 'Contas',
                'db_table': 'TBL_CONTA',
            },
        ),
        migrations.AddField(
            model_name='compra',
            name='conta',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='controle.Conta'),
            preserve_default=False,
        ),
    ]
