# Generated by Django 2.2.14 on 2020-11-22 20:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(db_column='STR_ITEM_COMPRA', max_length=500)),
                ('quantidade', models.IntegerField(db_column='N_QTDE', default=1)),
                ('desconto', models.FloatField(db_column='D_DESCONTO', default=0.0)),
                ('observacao', models.TextField(db_column='STR_OBSERVACAO')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
                'db_table': 'TBL_ITEM_COMPRA',
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_column='STR_NOME', max_length=100)),
                ('detalhe', models.TextField(db_column='STR_DETALHE')),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locais',
                'db_table': 'TBL_LOCAL',
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumo', models.CharField(db_column='STR_RESUMO', max_length=500)),
                ('data', models.DateField(db_column='DT_DATA_COMPRA', default=datetime.datetime(2020, 11, 22, 20, 30, 22, 506798))),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle.Local')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'db_table': 'TBL_COMPRA',
            },
        ),
    ]
