# Generated by Django 2.2.14 on 2020-11-22 20:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0005_auto_20201122_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='data',
            field=models.DateField(db_column='DT_DATA_COMPRA', default=django.utils.timezone.now),
        ),
    ]
