# Generated by Django 2.2.14 on 2020-11-22 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0006_auto_20201122_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcompra',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='controle.Category'),
        ),
        migrations.AddField(
            model_name='itemcompra',
            name='compra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='controle.Compra'),
        ),
    ]
