# Generated by Django 2.2.14 on 2020-11-22 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0007_auto_20201122_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcompra',
            name='valor',
            field=models.FloatField(db_column='D_VALOR', default=0.0),
        ),
    ]
